name: test  CI

on:
  pull_request:
  push:

jobs:
  build:
    runs-on: ubuntu-20.04
    strategy:
      matrix:
        app: [demo-clock]
    steps:
      - uses: actions/checkout@v2
      - name: npm setup
      - name: build
        run: |
          npm install -g html-minifier
          npm install -g inline-script
          inline-script-tags ${{ matrix.app }}/index.html ${{ matrix.app }}/bundle.html
          html-minifier ${{ matrix.app }}/bundle.html --config-file ${{ matrix.app }}/minify.json
