name: test  CI

on:
  pull_request:
  push:

jobs:
  build:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v2
      - name: Setup Python
        uses: actions/setup-python@v1
        with:
          python-version: '3.9'
      - name: Lint with prospector
        run: |
          python -m pip install --upgrade pip
          python -m pip install -r requirements.txt
          pip install prospector
          prospector -F --strictness veryhigh build.py
      - name: JS Minify
        uses: nizarmah/auto-minify@v2.1.1
        with:
          js_engine: uglify-js
          directory: apps
          overwrite: true
      - name: Compose webpage
        working-directory: apps
        run: |
          python -m pip install -r requirements.txt
          python build.py
