name: Bundle

on:
  pull_request:
  push:

jobs:
  bundle:
    name: ${{ matrix.app }}
    runs-on: ubuntu-20.04
    strategy:
      matrix:
        app: [ demo-clock ]
    steps:
      - uses: actions/checkout@v2
      - name: npm setup
        run: |
          npm install -g html-minifier
          npm install -g inline-scripts
      - name: bundle
        run: |
          inline-script-tags apps/${{ matrix.app }}/index.html apps/${{ matrix.app }}/bundle.html
          html-minifier apps/${{ matrix.app }}/bundle.html --config-file apps/${{ matrix.app }}/minify.json > apps/${{ matrix.app }}/bundle.html
          cat apps/${{ matrix.app }}/bundle.html
