name: Bundle

on:
  pull_request:
  push:

jobs:
  bundle:
    name: ${{ matrix.app }}
    runs-on: ubuntu-20.04
    strategy:
      matrix:
        app: [ demo-clock ]
    steps:
      - uses: actions/checkout@v2
 
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.9
 
      - name: Set up npm
        run: |
          npm install -g html-minifier
          npm install -g inline-scripts
    
      - name: bundle
        run: |
          python qr.py --htmldir=apps/${{ matrix.app }} --builddir=bundles --index=index.html
 
