name: Bundle

on:
  pull_request:
  push:

jobs:
  bundle:
    name: ${{ matrix.app }}
    runs-on: ubuntu-20.04
    strategy:
      matrix:
        app: [ demo-clock ]
    steps:
      - uses: actions/checkout@v2
      - name: npm setup
        run: |
          npm install -g html-minifier
          npm install -g inline-script
      - name: bundle
        run: |
          inline-script-tags ${{ matrix.app }}/index.html ${{ matrix.app }}/bundle.html
          html-minifier ${{ matrix.app }}/bundle.html --config-file ${{ matrix.app }}/minify.json
