name: Test Bundles

on:
    pull_request:

jobs:
  bundle:
    runs-on: ubuntu-24.04
    steps:
      - uses: actions/checkout@v2
      - name: build ci environment
        run: |
          docker build --pull --rm -t qrapps:ci .
      - name: generate QR
        run: |
          docker run --rm -it -v .:/src -w /src qrapps:ci qrs.py --htmldirs=apps --builddir=bundles
