name: test bundles

on:
    pull_request:

jobs:
  bundle:
    runs-on: windows-2022

    steps:
      - uses: actions/checkout@v2
 
      - name: set up python
        uses: actions/setup-python@v2
        with:
          python-version: 3.9
 
      - name: install python dependencies
        run: |
          python -m pip install --upgrade pip
          python -m pip install -r requirements.txt

      - name: set up npm
        run: |
          npm install -g html-minifier
          npm install -g inline-scripts

      - name: generate QR
        run: |
          python qr.py --htmldir=apps/demo-clock --builddir=bundles --index=index.html

      - name: generate README.md
        run: |
          python release.py

      - name: list
        run: |
          tree /f
 
