name: Test Bundles

on:
    pull_request:

jobs:
  bundle:
    runs-on: ubuntu-24.04
    steps:
      - uses: actions/checkout@v4
      - name: build ci environment
        run: |
          docker-compose build
      - name: generate QR
        run: |
          docker-compose run --rm qrs
