name: Prospector

on:
  pull_request:

jobs:
  prospector:
    runs-on: ubuntu-24.04
    steps:
      - uses: actions/checkout@v2
      - name: build ci environment
        run: |
          docker build --pull --rm -t qrapps:ci .
      - name: lint with prospector
        run: |
          docker run --rm -it -v .:/src -w /src --entrypoint=prospector qrapps:ci