name: Prospector

on:
  pull_request:

jobs:
  prospector:
    runs-on: ubuntu-24.04
    steps:
      - uses: actions/checkout@v4
      - name: build ci environment
        run: |
          docker-compose build
      - name: lint with prospector
        run: |
          docker-compose run --rm lint
