name: release bundles

on:
  push:
    branches: [ main ]

jobs:
  bundle:
    runs-on: windows-2022

    steps:
      - uses: actions/checkout@v2
 
      - name: set up python
        uses: actions/setup-python@v2
        with:
          python-version: 3.9
 
      - name: install python dependencies
        run: |
          python -m pip install --upgrade pip
          python -m pip install -r requirements.txt

      - name: set up npm
        run: |
          npm install -g uglify-js
          npm install -g html-minifier
          npm install -g inline-scripts

      - name: generate QR
        run: |
          python qrs.py --htmldirs=apps --builddir=bundles

      - name: generate README.md
        run: |
          Remove-Item -Path docs -Force -Recurse
          mv bundles docs
          git checkout -- docs/_config.yml
          python release.py
          tree /f docs

      - name: release
        run: |
          git config --global user.email "woldemar@mimas.ru"
          git config --global user.name "Vladimir Looze"
          git add docs
          git commit -m "release new bundles"
          git push origin main
 
