name: release bundles

on:
  push:
    branches: [ main ]

jobs:
  bundle:
    runs-on: windows-2022

    steps:
      - uses: actions/checkout@v2
 
      - name: set up python
        uses: actions/setup-python@v2
        with:
          python-version: 3.9
 
      - name: install python dependencies
        run: |
          python -m pip install --upgrade pip
          python -m pip install -r requirements.txt

      - name: set up npm
        run: |
          npm install -g html-minifier
          npm install -g inline-scripts

      - name: generate QR
        run: |
          python qr.py --htmldir=apps/demo-clock --builddir=bundles --index=index.html

      - name: generate README.md
        run: |
          rm -rf github.io
          mv bundles github.io
          python release.py
          tree /f github.io

      - name: release
        run: |
          git config --global user.email "woldemar@mimas.ru"
          git config --global user.name "Vladimir Looze"
          git add bundles
          git add README.md
          git commit -m "release new bundles"
          git push origin main
 
