name: Release Bundles

on:
  push:
    branches: [ main ]

jobs:
  bundle:
    runs-on: ubuntu-24.04
    steps:
      - uses: actions/checkout@v4
      - name: build ci environment
        run: |
          docker-compose build
      - name: generate QR
        run: |
          docker-compose run --rm qrs
      - name: generate README.md
        run: |
          rm -rf docs
          mv bundles docs
          sudo cp -at docs .google/*
          sudo git checkout -- docs/_config.yml
          docker-compose run --rm release
      - name: release
        run: |
          git config --global user.email "woldemar@mimas.ru"
          git config --global user.name "Vladimir Looze"
          git add docs
          git commit -m "release new bundles"
          git push --force origin main
