name: ruff

on:
  pull_request:

jobs:
  ruff:
    runs-on: ubuntu-24.04
    steps:
      - uses: actions/checkout@v4
      - name: build ci environment
        run: |
          docker compose build
      - name: lint with ruff
        run: |
          docker compose run --rm lint
